import { Product } from '../types';

// 🤖 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by scripts/generate-products.js
// To add/edit products, modify the catalog folders and run: node scripts/generate-products.js

export const products: Product[] = [
  {
    id: 'dt-cot-01',
    code: 'DT-COT-01',
    name: 'White Litchi Silk Cotton Blend Saree',
    category: 'saree',
    fabric: 'Cotton Blend',
    description: 'Elegant white cotton blend saree with litchi silk texture',
    longDescription: 'Beautiful white cotton blend saree features luxurious litchi silk texture. Perfect for casual wear and daily office settings.',
    price: 265,
    wholesaleMinQty: 10,
    wholesalePrice: 220,
    images: [
      '/src/assets/images/1/1_1.jpeg',
      '/src/assets/images/1/1_2.jpg',
      '/src/assets/images/1/1_3.jpg',
      '/src/assets/images/1/1_4.jpeg'
    ],
    colors: [
      'White',
      'Off White'
    ],
    isLatest: true,
    isBestSeller: true,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-sof-10',
    code: 'DT-SOF-10',
    name: 'Blue Soft Silk Festive Saree',
    category: 'saree',
    fabric: 'Soft Silk',
    description: 'Stunning blue soft silk saree for festive occasions',
    longDescription: 'Beautiful blue soft silk saree perfect for festive celebrations. Rich color and luxurious drape.',
    price: 470,
    wholesaleMinQty: 10,
    wholesalePrice: 395,
    images: [
      '/src/assets/images/10/10_1.jpeg'
    ],
    colors: [
      'Blue',
      'Royal Blue',
      'Teal'
    ],
    isLatest: false,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-lad-11',
    code: 'DT-LAD-11',
    name: 'Elegant Ladies Party Wear Saree',
    category: 'saree',
    fabric: 'Ladies Saree',
    description: 'Stylish ladies saree perfect for parties',
    longDescription: 'Contemporary ladies saree designed for modern women. Features trendy patterns and comfortable fabric.',
    price: 350,
    wholesaleMinQty: 10,
    wholesalePrice: 290,
    images: [
      '/src/assets/images/11/11_1.jpeg',
      '/src/assets/images/11/11_2.jpeg',
      '/src/assets/images/11/11_3.jpeg'
    ],
    colors: [
      'Multi',
      'Pink',
      'Blue'
    ],
    isLatest: true,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-lad-12',
    code: 'DT-LAD-12',
    name: 'Designer Ladies Festive Saree',
    category: 'saree',
    fabric: 'Ladies Saree',
    description: 'Designer ladies saree for festive celebrations',
    longDescription: 'Fashionable ladies saree with designer touch. Ideal for festive occasions and celebrations.',
    price: 365,
    wholesaleMinQty: 10,
    wholesalePrice: 305,
    images: [
      '/src/assets/images/12/12_1.jpeg',
      '/src/assets/images/12/12_2.jpeg',
      '/src/assets/images/12/12_3.jpeg'
    ],
    colors: [
      'Red',
      'Gold',
      'Orange'
    ],
    isLatest: true,
    isBestSeller: true,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-lad-13',
    code: 'DT-LAD-13',
    name: 'Traditional Ladies Wedding Saree',
    category: 'saree',
    fabric: 'Ladies Saree',
    description: 'Traditional ladies saree for wedding functions',
    longDescription: 'Classic ladies saree perfect for wedding ceremonies. Traditional patterns with modern comfort.',
    price: 380,
    wholesaleMinQty: 10,
    wholesalePrice: 315,
    images: [
      '/src/assets/images/13/13_1.jpeg',
      '/src/assets/images/13/13_2.jpeg',
      '/src/assets/images/13/13_3.jpeg'
    ],
    colors: [
      'Maroon',
      'Red',
      'Pink'
    ],
    isLatest: false,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-lad-14',
    code: 'DT-LAD-14',
    name: 'Modern Ladies Casual Saree',
    category: 'saree',
    fabric: 'Ladies Saree',
    description: 'Modern ladies saree for casual wear',
    longDescription: 'Comfortable ladies saree designed for daily wear. Easy to drape and maintain.',
    price: 340,
    wholesaleMinQty: 10,
    wholesalePrice: 285,
    images: [
      '/src/assets/images/14/14_1.jpeg'
    ],
    colors: [
      'Blue',
      'Green',
      'Yellow'
    ],
    isLatest: false,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-lad-15',
    code: 'DT-LAD-15',
    name: 'Premium Ladies Designer Saree',
    category: 'saree',
    fabric: 'Ladies Saree',
    description: 'Premium quality ladies designer saree',
    longDescription: 'Luxurious ladies saree with premium fabric and designer work. Perfect for special occasions.',
    price: 395,
    wholesaleMinQty: 10,
    wholesalePrice: 330,
    images: [
      '/src/assets/images/15/15_1.jpg'
    ],
    colors: [
      'Purple',
      'Gold',
      'Silver'
    ],
    isLatest: true,
    isBestSeller: true,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-art-16',
    code: 'DT-ART-16',
    name: 'Red Art Silk Festive Saree',
    category: 'saree',
    fabric: 'Art Silk',
    description: 'Vibrant red art silk saree for festive occasions',
    longDescription: 'Beautiful red art silk saree perfect for festivals. Rich color and smooth texture.',
    price: 320,
    wholesaleMinQty: 10,
    wholesalePrice: 270,
    images: [
      '/src/assets/images/16/16_1.jpeg'
    ],
    colors: [
      'Red',
      'Maroon',
      'Crimson'
    ],
    isLatest: false,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-art-17',
    code: 'DT-ART-17',
    name: 'Blue Art Silk Party Saree',
    category: 'saree',
    fabric: 'Art Silk',
    description: 'Elegant blue art silk saree for parties',
    longDescription: 'Stylish blue art silk saree ideal for party wear. Features attractive sheen and comfortable drape.',
    price: 330,
    wholesaleMinQty: 10,
    wholesalePrice: 275,
    images: [
      '/src/assets/images/17/17_1.jpeg'
    ],
    colors: [
      'Blue',
      'Navy',
      'Sky Blue'
    ],
    isLatest: true,
    isBestSeller: true,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-art-18',
    code: 'DT-ART-18',
    name: 'Green Art Silk Traditional Saree',
    category: 'saree',
    fabric: 'Art Silk',
    description: 'Traditional green art silk saree',
    longDescription: 'Classic green art silk saree with traditional appeal. Perfect for cultural events.',
    price: 310,
    wholesaleMinQty: 10,
    wholesalePrice: 265,
    images: [
      '/src/assets/images/18/18_1.jpeg'
    ],
    colors: [
      'Green',
      'Olive',
      'Mint'
    ],
    isLatest: false,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-art-19',
    code: 'DT-ART-19',
    name: 'Pink Art Silk Wedding Saree',
    category: 'saree',
    fabric: 'Art Silk',
    description: 'Charming pink art silk saree for weddings',
    longDescription: 'Lovely pink art silk saree designed for wedding celebrations. Elegant and affordable.',
    price: 340,
    wholesaleMinQty: 10,
    wholesalePrice: 285,
    images: [
      '/src/assets/images/19/19_1.jpeg'
    ],
    colors: [
      'Pink',
      'Rose',
      'Peach'
    ],
    isLatest: false,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-cot-02',
    code: 'DT-COT-02',
    name: 'Multicolor Cotton Blend Saree',
    category: 'saree',
    fabric: 'Cotton Blend',
    description: 'Vibrant multicolor cotton blend saree with artistic patterns',
    longDescription: 'This eye-catching multicolor cotton blend saree features vibrant artistic patterns. Perfect for casual and festive occasions.',
    price: 275,
    wholesaleMinQty: 10,
    wholesalePrice: 230,
    images: [
      '/src/assets/images/2/2_1.jpeg',
      '/src/assets/images/2/2_2.jpeg',
      '/src/assets/images/2/2_3.jpeg'
    ],
    colors: [
      'Multicolor',
      'Red',
      'Blue'
    ],
    isLatest: true,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-art-20',
    code: 'DT-ART-20',
    name: 'Golden Art Silk Designer Saree',
    category: 'saree',
    fabric: 'Art Silk',
    description: 'Luxurious golden art silk designer saree',
    longDescription: 'Glamorous golden art silk saree with designer patterns. Perfect for special occasions.',
    price: 350,
    wholesaleMinQty: 10,
    wholesalePrice: 295,
    images: [
      '/src/assets/images/20/20_1.jpeg'
    ],
    colors: [
      'Golden',
      'Gold',
      'Beige'
    ],
    isLatest: true,
    isBestSeller: true,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-org-21',
    code: 'DT-ORG-21',
    name: 'Floral Organza Designer Saree',
    category: 'saree',
    fabric: 'Organza',
    description: 'Beautiful floral organza saree with designer work',
    longDescription: 'Stunning organza saree featuring delicate floral patterns. Light, airy, and perfect for summer weddings.',
    price: 420,
    wholesaleMinQty: 10,
    wholesalePrice: 350,
    images: [
      '/src/assets/images/21/21_1.jpeg',
      '/src/assets/images/21/21_2.jpeg',
      '/src/assets/images/21/21_3.jpeg'
    ],
    colors: [
      'Multicolor',
      'Pink',
      'White'
    ],
    isLatest: true,
    isBestSeller: true,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-org-22',
    code: 'DT-ORG-22',
    name: 'Pastel Organza Party Wear Saree',
    category: 'saree',
    fabric: 'Organza',
    description: 'Elegant pastel organza saree for party wear',
    longDescription: 'Graceful pastel-colored organza saree ideal for parties and evening events. Features sheer elegance.',
    price: 410,
    wholesaleMinQty: 10,
    wholesalePrice: 340,
    images: [
      '/src/assets/images/22/22_1.jpg',
      '/src/assets/images/22/22_2.jpg',
      '/src/assets/images/22/22_3.jpeg'
    ],
    colors: [
      'Pastel',
      'Pink',
      'Blue',
      'Yellow'
    ],
    isLatest: true,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-uni-23',
    code: 'DT-UNI-23',
    name: 'Corporate Blue Uniform Saree',
    category: 'saree',
    fabric: 'Uniform Saree',
    description: 'Professional blue uniform saree for corporate wear',
    longDescription: 'Practical and elegant uniform saree designed for corporate and institutional use. Durable and easy-care.',
    price: 250,
    wholesaleMinQty: 10,
    wholesalePrice: 210,
    images: [
      '/src/assets/images/23/23_1.jpeg',
      '/src/assets/images/23/23_2.jpeg',
      '/src/assets/images/23/23_3.jpeg'
    ],
    colors: [
      'Blue',
      'Navy'
    ],
    isLatest: false,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-uni-24',
    code: 'DT-UNI-24',
    name: 'School Green Uniform Saree',
    category: 'saree',
    fabric: 'Uniform Saree',
    description: 'Comfortable green uniform saree for schools',
    longDescription: 'Quality uniform saree perfect for educational institutions. Long-lasting and low-maintenance.',
    price: 245,
    wholesaleMinQty: 10,
    wholesalePrice: 205,
    images: [
      '/src/assets/images/24/24_1.jpeg',
      '/src/assets/images/24/24_2.jpeg',
      '/src/assets/images/24/24_3.jpeg'
    ],
    colors: [
      'Green',
      'Dark Green'
    ],
    isLatest: false,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-sil-25',
    code: 'DT-SIL-25',
    name: 'Traditional Silk Weaving Saree',
    category: 'saree',
    fabric: 'Silk Weaving',
    description: 'Exquisite traditional silk weaving saree',
    longDescription: 'Masterfully crafted silk weaving saree with traditional patterns. Premium quality silk and intricate weaving work.',
    price: 520,
    wholesaleMinQty: 10,
    wholesalePrice: 435,
    images: [
      '/src/assets/images/25/25_1.jpg',
      '/src/assets/images/25/25_2.jpg',
      '/src/assets/images/25/25_3.jpg'
    ],
    colors: [
      'Red',
      'Gold',
      'Maroon'
    ],
    isLatest: true,
    isBestSeller: true,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-sil-26',
    code: 'DT-SIL-26',
    name: 'Premium Silk Weaving Designer Saree',
    category: 'saree',
    fabric: 'Silk Weaving',
    description: 'Premium silk weaving saree with designer patterns',
    longDescription: 'Luxurious silk weaving saree featuring designer motifs. Perfect for weddings and grand celebrations.',
    price: 550,
    wholesaleMinQty: 10,
    wholesalePrice: 460,
    images: [
      '/src/assets/images/26/26_1.jpeg'
    ],
    colors: [
      'Purple',
      'Gold',
      'Silver'
    ],
    isLatest: false,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-ban-27',
    code: 'DT-BAN-27',
    name: 'Royal Banarasi Silk Saree',
    category: 'saree',
    fabric: 'Banarasi Silk',
    description: 'Authentic royal Banarasi silk saree with zari work',
    longDescription: 'Magnificent Banarasi silk saree handwoven with traditional zari work. A timeless piece for wedding and special occasions. Premium quality guaranteed.',
    price: 850,
    wholesaleMinQty: 10,
    wholesalePrice: 720,
    images: [
      '/src/assets/images/27/27_1.jpg'
    ],
    colors: [
      'Red',
      'Gold',
      'Maroon'
    ],
    isLatest: true,
    isBestSeller: true,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-lin-28',
    code: 'DT-LIN-28',
    name: 'Natural Linen Casual Saree',
    category: 'saree',
    fabric: 'Linen',
    description: 'Comfortable natural linen saree for daily wear',
    longDescription: 'Eco-friendly linen saree perfect for daily wear and summer months. Breathable fabric with natural texture. Easy to maintain.',
    price: 380,
    wholesaleMinQty: 10,
    wholesalePrice: 315,
    images: [
      '/src/assets/images/28/28_1.jpeg',
      '/src/assets/images/28/28_2.jpeg'
    ],
    colors: [
      'Beige',
      'Brown',
      'Natural'
    ],
    isLatest: true,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-cot-03',
    code: 'DT-COT-03',
    name: 'Pink Cotton Blend Fancy Saree',
    category: 'saree',
    fabric: 'Cotton Blend',
    description: 'Charming pink cotton blend saree with fancy border',
    longDescription: 'Delicate pink cotton blend saree with beautiful fancy border work. Ideal for daily wear and office settings.',
    price: 280,
    wholesaleMinQty: 10,
    wholesalePrice: 235,
    images: [
      '/src/assets/images/3/3_1.jpeg',
      '/src/assets/images/3/3_2.jpeg',
      '/src/assets/images/3/3_3.jpeg'
    ],
    colors: [
      'Pink',
      'Rose',
      'Peach'
    ],
    isLatest: false,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-cot-04',
    code: 'DT-COT-04',
    name: 'Blue Cotton Blend Designer Saree',
    category: 'saree',
    fabric: 'Cotton Blend',
    description: 'Stylish blue cotton blend saree with designer patterns',
    longDescription: 'Modern blue cotton blend saree featuring contemporary designer patterns. Perfect blend of style and comfort.',
    price: 290,
    wholesaleMinQty: 10,
    wholesalePrice: 240,
    images: [
      '/src/assets/images/4/4_1.jpeg',
      '/src/assets/images/4/4_2.jpeg',
      '/src/assets/images/4/4_3.jpeg'
    ],
    colors: [
      'Blue',
      'Navy',
      'Sky Blue'
    ],
    isLatest: false,
    isBestSeller: true,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-cot-05',
    code: 'DT-COT-05',
    name: 'Green Cotton Blend Traditional Saree',
    category: 'saree',
    fabric: 'Cotton Blend',
    description: 'Traditional green cotton blend saree with ethnic motifs',
    longDescription: 'Classic green cotton blend saree adorned with traditional ethnic motifs. Comfortable for all-day wear.',
    price: 270,
    wholesaleMinQty: 10,
    wholesalePrice: 225,
    images: [
      '/src/assets/images/5/5_1.jpeg',
      '/src/assets/images/5/5_2.jpeg'
    ],
    colors: [
      'Green',
      'Olive',
      'Mint'
    ],
    isLatest: false,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-sof-06',
    code: 'DT-SOF-06',
    name: 'Red Soft Silk Weaving Saree',
    category: 'saree',
    fabric: 'Soft Silk',
    description: 'Luxurious red soft silk saree with intricate weaving',
    longDescription: 'Stunning red soft silk saree featuring intricate traditional weaving patterns. Perfect for weddings and special occasions.',
    price: 450,
    wholesaleMinQty: 10,
    wholesalePrice: 380,
    images: [
      '/src/assets/images/6/6_1.jpeg',
      '/src/assets/images/6/6_2.jpg',
      '/src/assets/images/6/6_3.jpg'
    ],
    colors: [
      'Red',
      'Maroon',
      'Crimson'
    ],
    isLatest: true,
    isBestSeller: true,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-sof-07',
    code: 'DT-SOF-07',
    name: 'Golden Soft Silk Party Wear Saree',
    category: 'saree',
    fabric: 'Soft Silk',
    description: 'Elegant golden soft silk saree for party wear',
    longDescription: 'Glamorous golden soft silk saree with rich texture. Ideal for parties, receptions, and festive celebrations.',
    price: 480,
    wholesaleMinQty: 10,
    wholesalePrice: 400,
    images: [
      '/src/assets/images/7/7_1.jpeg',
      '/src/assets/images/7/7_2.jpg',
      '/src/assets/images/7/7_3.jpg'
    ],
    colors: [
      'Golden',
      'Gold',
      'Beige'
    ],
    isLatest: true,
    isBestSeller: true,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-sof-08',
    code: 'DT-SOF-08',
    name: 'Purple Soft Silk Designer Saree',
    category: 'saree',
    fabric: 'Soft Silk',
    description: 'Beautiful purple soft silk saree with designer work',
    longDescription: 'Exquisite purple soft silk saree featuring designer embellishments. Perfect for special events and celebrations.',
    price: 460,
    wholesaleMinQty: 10,
    wholesalePrice: 385,
    images: [
      '/src/assets/images/8/8_1.jpeg',
      '/src/assets/images/8/8_2.jpg',
      '/src/assets/images/8/8_3.jpg'
    ],
    colors: [
      'Purple',
      'Violet',
      'Lavender'
    ],
    isLatest: false,
    isBestSeller: false,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  },
  {
    id: 'dt-sof-09',
    code: 'DT-SOF-09',
    name: 'Pink Soft Silk Wedding Saree',
    category: 'saree',
    fabric: 'Soft Silk',
    description: 'Gorgeous pink soft silk saree for weddings',
    longDescription: 'Magnificent pink soft silk saree designed for wedding occasions. Features elegant work and premium silk quality.',
    price: 495,
    wholesaleMinQty: 10,
    wholesalePrice: 415,
    images: [
      '/src/assets/images/9/9_1.jpeg',
      '/src/assets/images/9/9_2.jpg',
      '/src/assets/images/9/9_3.jpg'
    ],
    colors: [
      'Pink',
      'Rose Pink',
      'Magenta'
    ],
    isLatest: true,
    isBestSeller: true,
    specifications: {
      length: '5.5 meters',
      blouse: '80 cm unstitched matching fabric',
      work: 'Traditional design and weaving',
      washCare: 'Hand Wash or Dry Clean',
      purity: 'Pure Fabric'
    }
  }
];  // Use single quotes
